/*
 * Square Connect API
 *
 * Client library for accessing the Square Connect APIs
 *
 * API version: 2.0
 * Contact: developers@squareup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package square

// Describes when the loyalty program expires.
type LoyaltyProgramExpirationPolicy struct {
	// The duration of time before points expire, in RFC 3339 format.
	ExpirationDuration string `json:"expiration_duration"`
}
