/*
 * Square Connect API
 *
 * Client library for accessing the Square Connect APIs
 *
 * API version: 2.0
 * Contact: developers@squareup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package square

type OrderCreated struct {
	// The order's unique ID.
	OrderId string `json:"order_id,omitempty"`
	// Version number which is incremented each time an update is committed to the order. Orders that were not created through the API will not include a version and thus cannot be updated.  [Read more about working with versions](https://developer.squareup.com/docs/docs/orders-api/manage-orders#update-orders)
	Version int32 `json:"version,omitempty"`
	// The ID of the merchant location this order is associated with.
	LocationId string `json:"location_id,omitempty"`
	// The state of the order. See [OrderState](#type-orderstate) for possible values
	State string `json:"state,omitempty"`
	// Timestamp for when the order was created in RFC 3339 format.
	CreatedAt string `json:"created_at,omitempty"`
}
