/*
 * Square Connect API
 *
 * Client library for accessing the Square Connect APIs
 *
 * API version: 2.0
 * Contact: developers@squareup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package square

// Contains some brief information about a Customer Group with its identifier included.
type CustomerGroupInfo struct {
	// The ID of the Customer Group.
	Id string `json:"id"`
	// The name of the Customer Group.
	Name string `json:"name"`
}
