/*
 * Square Connect API
 *
 * Client library for accessing the Square Connect APIs
 *
 * API version: 2.0
 * Contact: developers@squareup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package square

type V1UpdateModifierListRequestSelectionType string

// List of V1UpdateModifierListRequestSelectionType
const (
	SINGLE_V1UpdateModifierListRequestSelectionType V1UpdateModifierListRequestSelectionType = "SINGLE"
	MULTIPLE_V1UpdateModifierListRequestSelectionType V1UpdateModifierListRequestSelectionType = "MULTIPLE"
)
