/*
 * Square Connect API
 *
 * Client library for accessing the Square Connect APIs
 *
 * API version: 2.0
 * Contact: developers@squareup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package square
// LocationStatus : The status of the location, whether a location is active or inactive.
type LocationStatus string

// List of LocationStatus
const (
	ACTIVE_LocationStatus LocationStatus = "ACTIVE"
	INACTIVE_LocationStatus LocationStatus = "INACTIVE"
)
