/*
 * Square Connect API
 *
 * Client library for accessing the Square Connect APIs
 *
 * API version: 2.0
 * Contact: developers@squareup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package square

// Represents a unit of measurement to use with a quantity, such as ounces or inches. Exactly one of the following fields are required: `custom_unit`, `area_unit`, `length_unit`, `volume_unit`, and `weight_unit`.
type MeasurementUnit struct {
	CustomUnit *MeasurementUnitCustom `json:"custom_unit,omitempty"`
	// Represents a standard area unit. See [MeasurementUnitArea](#type-measurementunitarea) for possible values
	AreaUnit string `json:"area_unit,omitempty"`
	// Represents a standard length unit. See [MeasurementUnitLength](#type-measurementunitlength) for possible values
	LengthUnit string `json:"length_unit,omitempty"`
	// Represents a standard volume unit. See [MeasurementUnitVolume](#type-measurementunitvolume) for possible values
	VolumeUnit string `json:"volume_unit,omitempty"`
	// Represents a standard unit of weight or mass. See [MeasurementUnitWeight](#type-measurementunitweight) for possible values
	WeightUnit string `json:"weight_unit,omitempty"`
	// Reserved for API integrations that lack the ability to specify a real measurement unit See [MeasurementUnitGeneric](#type-measurementunitgeneric) for possible values
	GenericUnit string `json:"generic_unit,omitempty"`
	// Represents a standard unit of time. See [MeasurementUnitTime](#type-measurementunittime) for possible values
	TimeUnit string `json:"time_unit,omitempty"`
	// Represents the type of the measurement unit. See [MeasurementUnitUnitType](#type-measurementunitunittype) for possible values
	Type_ string `json:"type,omitempty"`
}
