/*
 * Square Connect API
 *
 * Client library for accessing the Square Connect APIs
 *
 * API version: 2.0
 * Contact: developers@squareup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package square

type V1ListOrdersRequest struct {
	// TThe order in which payments are listed in the response. See [SortOrder](#type-sortorder) for possible values
	Order string `json:"order,omitempty"`
	// The maximum number of payments to return in a single response. This value cannot exceed 200.
	Limit int32 `json:"limit,omitempty"`
	// A pagination cursor to retrieve the next set of results for your original query to the endpoint.
	BatchToken string `json:"batch_token,omitempty"`
}
