/*
 * Square Connect API
 *
 * Client library for accessing the Square Connect APIs
 *
 * API version: 2.0
 * Contact: developers@squareup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package square

type V1ItemColor string

// List of V1ItemColor
const (
	9DA2A6__V1ItemColor V1ItemColor = "9da2a6"
	4AB200__V1ItemColor V1ItemColor = "4ab200"
	0B8000__V1ItemColor V1ItemColor = "0b8000"
	2952CC__V1ItemColor V1ItemColor = "2952cc"
	A82EE5_V1ItemColor V1ItemColor = "a82ee5"
	E5457A_V1ItemColor V1ItemColor = "e5457a"
	B21212_V1ItemColor V1ItemColor = "b21212"
	593C00__V1ItemColor V1ItemColor = "593c00"
	E5_BF00_V1ItemColor V1ItemColor = "e5BF00"
)
