/*
 * Square Connect API
 *
 * Client library for accessing the Square Connect APIs
 *
 * API version: 2.0
 * Contact: developers@squareup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package square

// Defines the fields included in the response body from the [BulkRetrieveCustomers](https://developer.squareup.com/reference/square_2024-07-17/customers-api/bulk-retrieve-customers) endpoint.
type BulkRetrieveCustomersResponse struct {
	// A map of responses that correspond to individual retrieve requests, represented by key-value pairs.  Each key is the customer ID that was specified for a retrieve request and each value is the corresponding response. If the request succeeds, the value is the requested customer profile. If the request fails, the value contains any errors that occurred during the request.
	Responses map[string]RetrieveCustomerResponse `json:"responses,omitempty"`
	// Any top-level errors that prevented the bulk operation from running.
	Errors []ModelError `json:"errors,omitempty"`
}
