/*
 * Square Connect API
 *
 * Client library for accessing the Square Connect APIs
 *
 * API version: 2.0
 * Contact: developers@squareup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package square

// Represents a booking as a time-bound service contract for a seller's staff member to provide a specified service at a given location to a requesting customer in one or more appointment segments.
type Booking struct {
	// A unique ID of this object representing a booking.
	Id string `json:"id,omitempty"`
	// The revision number for the booking used for optimistic concurrency.
	Version int32 `json:"version,omitempty"`
	// The status of the booking, describing where the booking stands with respect to the booking state machine. See [BookingStatus](#type-bookingstatus) for possible values
	Status string `json:"status,omitempty"`
	// The timestamp specifying the creation time of this booking.
	CreatedAt string `json:"created_at,omitempty"`
	// The timestamp specifying the most recent update time of this booking.
	UpdatedAt string `json:"updated_at,omitempty"`
	// The timestamp specifying the starting time of this booking.
	StartAt string `json:"start_at,omitempty"`
	// The ID of the `Location` object representing the location where the booked service is provided.
	LocationId string `json:"location_id,omitempty"`
	// The ID of the `Customer` object representing the customer attending this booking
	CustomerId string `json:"customer_id,omitempty"`
	// The free-text field for the customer to supply notes about the booking. For example, the note can be preferences that cannot be expressed by supported attributes of a relevant `CatalogObject` instance.
	CustomerNote string `json:"customer_note,omitempty"`
	// The free-text field for the seller to supply notes about the booking. For example, the note can be preferences that cannot be expressed by supported attributes of a specific `CatalogObject` instance. This field should not be visible to customers.
	SellerNote string `json:"seller_note,omitempty"`
	// A list of appointment segments for this booking.
	AppointmentSegments []AppointmentSegment `json:"appointment_segments,omitempty"`
}
