/*
 * Square Connect API
 *
 * Client library for accessing the Square Connect APIs
 *
 * API version: 2.0
 * Contact: developers@squareup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package square

// V1AdjustInventoryRequest
type V1AdjustInventoryRequest struct {
	// The number to adjust the variation's quantity by.
	QuantityDelta float64 `json:"quantity_delta,omitempty"`
	// The reason for the inventory adjustment. See [V1AdjustInventoryRequestAdjustmentType](#type-v1adjustinventoryrequestadjustmenttype) for possible values
	AdjustmentType string `json:"adjustment_type,omitempty"`
	// A note about the inventory adjustment.
	Memo string `json:"memo,omitempty"`
}
