/*
 * Square Connect API
 *
 * Client library for accessing the Square Connect APIs
 *
 * API version: 2.0
 * Contact: developers@squareup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package square
// InvoiceSortField : Field to use for sorting.
type InvoiceSortField string

// List of InvoiceSortField
const (
	DATE_InvoiceSortField InvoiceSortField = "INVOICE_SORT_DATE"
)
