/*
 * Square Connect API
 *
 * Client library for accessing the Square Connect APIs
 *
 * API version: 2.0
 * Contact: developers@squareup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package square

type CheckAppointmentsOnboardedResponse struct {
	// Indicates whether the seller has enabled the Square Appointments service (`true`) or not (`false`).
	AppointmentsOnboarded bool `json:"appointments_onboarded,omitempty"`
	// Any errors that occurred during the request.
	Errors []ModelError `json:"errors,omitempty"`
}
