/*
 * Square Connect API
 *
 * Client library for accessing the Square Connect APIs
 *
 * API version: 2.0
 * Contact: developers@squareup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package square

type UpdateItemTaxesRequest struct {
	// IDs for the CatalogItems associated with the CatalogTax objects being updated.
	ItemIds []string `json:"item_ids"`
	// IDs of the CatalogTax objects to enable.
	TaxesToEnable []string `json:"taxes_to_enable,omitempty"`
	// IDs of the CatalogTax objects to disable.
	TaxesToDisable []string `json:"taxes_to_disable,omitempty"`
}
