/*
 * Square Connect API
 *
 * Client library for accessing the Square Connect APIs
 *
 * API version: 2.0
 * Contact: developers@squareup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package square

// V1CashDrawerEvent
type V1CashDrawerEvent struct {
	// The event's unique ID.
	Id string `json:"id,omitempty"`
	// The ID of the employee that created the event.
	EmployeeId string `json:"employee_id,omitempty"`
	// The type of event that occurred. See [V1CashDrawerEventEventType](#type-v1cashdrawereventeventtype) for possible values
	EventType string `json:"event_type,omitempty"`
	EventMoney *V1Money `json:"event_money,omitempty"`
	// The time when the event occurred, in ISO 8601 format.
	CreatedAt string `json:"created_at,omitempty"`
	// An optional description of the event, entered by the employee that created it.
	Description string `json:"description,omitempty"`
}
