/*
 * Square Connect API
 *
 * Client library for accessing the Square Connect APIs
 *
 * API version: 2.0
 * Contact: developers@squareup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package square

// Describes a subscription plan. For more information, see [Set Up and Manage a Subscription Plan](/docs/subscriptions-api/setup-plan).
type CatalogSubscriptionPlan struct {
	// The name of the plan.
	Name string `json:"name,omitempty"`
	// A list of SubscriptionPhase containing the `SubscriptionPhase` for this plan.
	Phases []SubscriptionPhase `json:"phases,omitempty"`
}
