/*
 * Square Connect API
 *
 * Client library for accessing the Square Connect APIs
 *
 * API version: 2.0
 * Contact: developers@squareup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package square

// Represents a period of time during which a business location is open.
type BusinessHoursPeriod struct {
	// The day of week for this time period. See [DayOfWeek](#type-dayofweek) for possible values
	DayOfWeek string `json:"day_of_week,omitempty"`
	// The start time of a business hours period, specified in local time using partial-time RFC 3339 format.
	StartLocalTime string `json:"start_local_time,omitempty"`
	// The end time of a business hours period, specified in local time using partial-time RFC 3339 format.
	EndLocalTime string `json:"end_local_time,omitempty"`
}
