/*
 * Square Connect API
 *
 * Client library for accessing the Square Connect APIs
 *
 * API version: 2.0
 * Contact: developers@squareup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package square

// Filter based on [order fulfillment](https://developer.squareup.com/reference/square_2024-07-17/objects/Fulfillment) information.
type SearchOrdersFulfillmentFilter struct {
	// A list of [fulfillment types](https://developer.squareup.com/reference/square_2024-07-17/enums/FulfillmentType) to filter for. The list returns orders if any of its fulfillments match any of the fulfillment types listed in this field.
	FulfillmentTypes []string `json:"fulfillment_types,omitempty"`
	// A list of [fulfillment states](https://developer.squareup.com/reference/square_2024-07-17/enums/FulfillmentState) to filter for. The list returns orders if any of its fulfillments match any of the fulfillment states listed in this field.
	FulfillmentStates []string `json:"fulfillment_states,omitempty"`
}
