/*
 * Square Connect API
 *
 * Client library for accessing the Square Connect APIs
 *
 * API version: 2.0
 * Contact: developers@squareup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package square

// Contains metadata about a particular [Event](https://developer.squareup.com/reference/square_2024-07-17/objects/Event).
type EventMetadata struct {
	// A unique ID for the event.
	EventId string `json:"event_id,omitempty"`
	// The API version of the event. This corresponds to the default API version of the developer application at the time when the event was created.
	ApiVersion string `json:"api_version,omitempty"`
}
