/*
 * Square Connect API
 *
 * Client library for accessing the Square Connect APIs
 *
 * API version: 2.0
 * Contact: developers@squareup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package square

type Location struct {
	// The Square-issued ID of the location.
	Id string `json:"id,omitempty"`
	// The name of the location. This information appears in the dashboard as the nickname.
	Name string `json:"name,omitempty"`
	Address *Address `json:"address,omitempty"`
	// The [IANA Timezone](https://www.iana.org/time-zones) identifier for the timezone of the location.
	Timezone string `json:"timezone,omitempty"`
	// The Square features that are enabled for the location. See `LocationCapability` for possible values. See [LocationCapability](#type-locationcapability) for possible values
	Capabilities []string `json:"capabilities,omitempty"`
	// The status of the location, either active or inactive. See [LocationStatus](#type-locationstatus) for possible values
	Status string `json:"status,omitempty"`
	// The time when the location was created, in RFC 3339 format.
	CreatedAt string `json:"created_at,omitempty"`
	// The ID of the merchant that owns the location.
	MerchantId string `json:"merchant_id,omitempty"`
	// The country of the location, in ISO 3166-1-alpha-2 format.  See `Country` for possible values. See [Country](#type-country) for possible values
	Country string `json:"country,omitempty"`
	// The language associated with the location, in [BCP 47 format](https://tools.ietf.org/html/bcp47#appendix-A).
	LanguageCode string `json:"language_code,omitempty"`
	// The currency used for all transactions at this location, in ISO 4217 format. See `Currency` for possible values. See [Currency](#type-currency) for possible values
	Currency string `json:"currency,omitempty"`
	// The phone number of the location in human readable format.
	PhoneNumber string `json:"phone_number,omitempty"`
	// The business name of the location This is the name visible to the customers of the location. For example, this name appears on customer receipts.
	BusinessName string `json:"business_name,omitempty"`
	// The type of the location, either physical or mobile. See [LocationType](#type-locationtype) for possible values
	Type_ string `json:"type,omitempty"`
	// The website URL of the location.
	WebsiteUrl string `json:"website_url,omitempty"`
	BusinessHours *BusinessHours `json:"business_hours,omitempty"`
	// The email of the location. This email is visible to the customers of the location. For example, the email appears on customer receipts.
	BusinessEmail string `json:"business_email,omitempty"`
	// The description of the location.
	Description string `json:"description,omitempty"`
	// The Twitter username of the location without the '&#64;' symbol.
	TwitterUsername string `json:"twitter_username,omitempty"`
	// The Instagram username of the location without the '&#64;' symbol.
	InstagramUsername string `json:"instagram_username,omitempty"`
	// The Facebook profile URL of the location. The URL should begin with 'facebook.com/'.
	FacebookUrl string `json:"facebook_url,omitempty"`
	Coordinates *Coordinates `json:"coordinates,omitempty"`
	// The URL of the logo image for the location. The Seller must choose this logo in the Seller dashboard (Receipts section) for the logo to appear on transactions (such as receipts, invoices) that Square generates on behalf of the Seller. This image should have an aspect ratio close to 1:1 and is recommended to be at least 200x200 pixels.
	LogoUrl string `json:"logo_url,omitempty"`
	// The URL of the Point of Sale background image for the location.
	PosBackgroundUrl string `json:"pos_background_url,omitempty"`
	// The merchant category code (MCC) of the location, as standardized by ISO 18245. The MCC describes the kind of goods or services sold at the location.
	Mcc string `json:"mcc,omitempty"`
	// The URL of a full-format logo image for the location. The Seller must choose this logo in the Seller dashboard (Receipts section) for the logo to appear on transactions (such as receipts, invoices) that Square generates on behalf of the Seller. This image can have an aspect ratio of 2:1 or greater and is recommended to be at least 1280x648 pixels.
	FullFormatLogoUrl string `json:"full_format_logo_url,omitempty"`
}
