/*
 * Square Connect API
 *
 * Client library for accessing the Square Connect APIs
 *
 * API version: 2.0
 * Contact: developers@squareup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package square

type V1AdjustInventoryRequestAdjustmentType string

// List of V1AdjustInventoryRequestAdjustmentType
const (
	SALE_V1AdjustInventoryRequestAdjustmentType V1AdjustInventoryRequestAdjustmentType = "SALE"
	RECEIVE_STOCK_V1AdjustInventoryRequestAdjustmentType V1AdjustInventoryRequestAdjustmentType = "RECEIVE_STOCK"
	MANUAL_ADJUST_V1AdjustInventoryRequestAdjustmentType V1AdjustInventoryRequestAdjustmentType = "MANUAL_ADJUST"
)
