/*
 * Square Connect API
 *
 * Client library for accessing the Square Connect APIs
 *
 * API version: 2.0
 * Contact: developers@squareup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package square

// V1BankAccount
type V1BankAccount struct {
	// The bank account's Square-issued ID.
	Id string `json:"id,omitempty"`
	// The Square-issued ID of the merchant associated with the bank account.
	MerchantId string `json:"merchant_id,omitempty"`
	// The name of the bank that manages the account.
	BankName string `json:"bank_name,omitempty"`
	// The name associated with the bank account.
	Name string `json:"name,omitempty"`
	// The bank account's routing number.
	RoutingNumber string `json:"routing_number,omitempty"`
	// The last few digits of the bank account number.
	AccountNumberSuffix string `json:"account_number_suffix,omitempty"`
	// The currency code of the currency associated with the bank account, in ISO 4217 format. For example, the currency code for US dollars is USD.
	CurrencyCode string `json:"currency_code,omitempty"`
	// The bank account's type (for example, savings or checking). See [V1BankAccountType](#type-v1bankaccounttype) for possible values
	Type_ string `json:"type,omitempty"`
}
