/*
 * Square Connect API
 *
 * Client library for accessing the Square Connect APIs
 *
 * API version: 2.0
 * Contact: developers@squareup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package square

// Represents a [DeleteCustomerCustomAttributeDefinition](https://developer.squareup.com/reference/square_2024-07-17/customer-custom-attributes-api/delete-customer-custom-attribute-definition) request.
type DeleteCustomerCustomAttributeDefinitionRequest struct{}
