/*
 * Square Connect API
 *
 * Client library for accessing the Square Connect APIs
 *
 * API version: 2.0
 * Contact: developers@squareup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package square

// Represents the payment details of a card to be used for payments. These details are determined by the `card_nonce` generated by `SqPaymentForm`.
type Card struct {
	// Unique ID for this card. Generated by Square.
	Id string `json:"id,omitempty"`
	// The card's brand. See [CardBrand](#type-cardbrand) for possible values
	CardBrand string `json:"card_brand,omitempty"`
	// The last 4 digits of the card number.
	Last4 string `json:"last_4,omitempty"`
	// The expiration month of the associated card as an integer between 1 and 12.
	ExpMonth int64 `json:"exp_month,omitempty"`
	// The four-digit year of the card's expiration date.
	ExpYear int64 `json:"exp_year,omitempty"`
	// The name of the cardholder.
	CardholderName string `json:"cardholder_name,omitempty"`
	BillingAddress *Address `json:"billing_address,omitempty"`
	// __Not currently set.__ Intended as a Square-assigned identifier, based on the card number, to identify the card across multiple locations within a single application.
	Fingerprint string `json:"fingerprint,omitempty"`
	// The type of the card. The Card object includes this field only in response to Payments API calls. See [CardType](#type-cardtype) for possible values
	CardType string `json:"card_type,omitempty"`
	// Indicates whether the Card is prepaid or not. The Card object includes this field only in response to Payments API calls. See [CardPrepaidType](#type-cardprepaidtype) for possible values
	PrepaidType string `json:"prepaid_type,omitempty"`
	// The first six digits of the card number, known as the Bank Identification Number (BIN). Only the Payments API returns this field.
	Bin string `json:"bin,omitempty"`
}
