/*
 * Square Connect API
 *
 * Client library for accessing the Square Connect APIs
 *
 * API version: 2.0
 * Contact: developers@squareup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package square

type ListTeamMemberBookingProfilesResponse struct {
	// The list of team member booking profiles.
	TeamMemberBookingProfiles []TeamMemberBookingProfile `json:"team_member_booking_profiles,omitempty"`
	// The cursor for paginating through the results.
	Cursor string `json:"cursor,omitempty"`
	// Any errors that occurred during the request.
	Errors []ModelError `json:"errors,omitempty"`
}
