/*
 * Square Connect API
 *
 * Client library for accessing the Square Connect APIs
 *
 * API version: 2.0
 * Contact: developers@squareup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package square

// Represents a Square seller.
type Merchant struct {
	// The Square-issued ID of the merchant.
	Id string `json:"id,omitempty"`
	// The business name of the merchant.
	BusinessName string `json:"business_name,omitempty"`
	// The country code associated with the merchant account, in ISO 3166 format. See [Country](#type-country) for possible values
	Country string `json:"country"`
	// The language code associated with the merchant account, in BCP 47 format.
	LanguageCode string `json:"language_code,omitempty"`
	// The currency associated with the merchant account, in ISO 4217 format. See [Currency](#type-currency) for possible values
	Currency string `json:"currency,omitempty"`
	// The merchant status, active or inactive. See [MerchantStatus](#type-merchantstatus) for possible values
	Status string `json:"status,omitempty"`
	// The ID of the main `Location` for this merchant.
	MainLocationId string `json:"main_location_id,omitempty"`
}
