/*
 * Square Connect API
 *
 * Client library for accessing the Square Connect APIs
 *
 * API version: 2.0
 * Contact: developers@squareup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package square

type V1FeeInclusionType string

// List of V1FeeInclusionType
const (
	ADDITIVE_V1FeeInclusionType V1FeeInclusionType = "ADDITIVE"
	INCLUSIVE_V1FeeInclusionType V1FeeInclusionType = "INCLUSIVE"
)
