/*
 * Square Connect API
 *
 * Client library for accessing the Square Connect APIs
 *
 * API version: 2.0
 * Contact: developers@squareup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package square

// V1Discount
type V1Discount struct {
	// The discount's unique ID.
	Id string `json:"id,omitempty"`
	// The discount's name.
	Name string `json:"name,omitempty"`
	// The rate of the discount, as a string representation of a decimal number. A value of 0.07 corresponds to a rate of 7%. This rate is 0 if discount_type is VARIABLE_PERCENTAGE.
	Rate string `json:"rate,omitempty"`
	AmountMoney *V1Money `json:"amount_money,omitempty"`
	// Indicates whether the discount is a FIXED value or entered at the time of sale. See [V1DiscountDiscountType](#type-v1discountdiscounttype) for possible values
	DiscountType string `json:"discount_type,omitempty"`
	// Indicates whether a mobile staff member needs to enter their PIN to apply the discount to a payment.
	PinRequired bool `json:"pin_required,omitempty"`
	// The color of the discount's display label in Square Point of Sale, if not the default color. The default color is 9da2a6. See [V1DiscountColor](#type-v1discountcolor) for possible values
	Color string `json:"color,omitempty"`
	// The ID of the CatalogObject in the Connect v2 API. Objects that are shared across multiple locations share the same v2 ID.
	V2Id string `json:"v2_id,omitempty"`
}
