/*
 * Square Connect API
 *
 * Client library for accessing the Square Connect APIs
 *
 * API version: 2.0
 * Contact: developers@squareup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package square

// Filter by current Order `state`.
type SearchOrdersStateFilter struct {
	// States to filter for. See [OrderState](#type-orderstate) for possible values
	States []string `json:"states"`
}
