/*
 * Square Connect API
 *
 * Client library for accessing the Square Connect APIs
 *
 * API version: 2.0
 * Contact: developers@squareup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package square

// V1ItemImage
type V1ItemImage struct {
	// The image's unique ID.
	Id string `json:"id,omitempty"`
	// The image's publicly accessible URL.
	Url string `json:"url,omitempty"`
}
