/*
 * Square Connect API
 *
 * Client library for accessing the Square Connect APIs
 *
 * API version: 2.0
 * Contact: developers@squareup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package square
// InvoiceRequestType : Indicates the type of the payment request. An invoice supports the following payment request combinations: - 1 balance - 1 deposit with 1 balance - 2 - 12 installments - 1 deposit with 2 - 12 installments  For more information,  see [Payment requests](https://developer.squareup.com/docs/docs/invoices-api/overview#payment-requests).
type InvoiceRequestType string

// List of InvoiceRequestType
const (
	BALANCE_InvoiceRequestType InvoiceRequestType = "BALANCE"
	DEPOSIT_InvoiceRequestType InvoiceRequestType = "DEPOSIT"
	INSTALLMENT_InvoiceRequestType InvoiceRequestType = "INSTALLMENT"
)
