/*
 * Square Connect API
 *
 * Client library for accessing the Square Connect APIs
 *
 * API version: 2.0
 * Contact: developers@squareup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package square

// Defines the body parameters that can be included in requests to the [BulkDeleteCustomers](https://developer.squareup.com/reference/square_2024-07-17/customers-api/bulk-delete-customers) endpoint.
type BulkDeleteCustomersRequest struct {
	// The IDs of the [customer profiles](https://developer.squareup.com/reference/square_2024-07-17/objects/Customer) to delete.
	CustomerIds []string `json:"customer_ids"`
}
