/*
 * Square Connect API
 *
 * Client library for accessing the Square Connect APIs
 *
 * API version: 2.0
 * Contact: developers@squareup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package square

type V1DiscountDiscountType string

// List of V1DiscountDiscountType
const (
	FIXED_V1DiscountDiscountType V1DiscountDiscountType = "FIXED"
	VARIABLE_PERCENTAGE_V1DiscountDiscountType V1DiscountDiscountType = "VARIABLE_PERCENTAGE"
	VARIABLE_AMOUNT_V1DiscountDiscountType V1DiscountDiscountType = "VARIABLE_AMOUNT"
)
