/*
 * Square Connect API
 *
 * Client library for accessing the Square Connect APIs
 *
 * API version: 2.0
 * Contact: developers@squareup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package square

// Defines output parameters in a response from the [RetrieveSubscription](https://developer.squareup.com/reference/square_2024-07-17/subscriptions-api/retrieve-subscription) endpoint.
type RetrieveSubscriptionResponse struct {
	// Errors encountered during the request.
	Errors       []ModelError  `json:"errors,omitempty"`
	Subscription *Subscription `json:"subscription,omitempty"`
}
