/*
 * Square Connect API
 *
 * Client library for accessing the Square Connect APIs
 *
 * API version: 2.0
 * Contact: developers@squareup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package square

// Describes changes to subscription and billing states.
type SubscriptionEvent struct {
	// The ID of the subscription event.
	Id string `json:"id"`
	// Type of the subscription event. See [SubscriptionEventSubscriptionEventType](#type-subscriptioneventsubscriptioneventtype) for possible values
	SubscriptionEventType string `json:"subscription_event_type"`
	// The date, in YYYY-MM-DD format (for example, 2013-01-15), when the subscription event went into effect.
	EffectiveDate string `json:"effective_date"`
	// The ID of the subscription plan associated with the subscription.
	PlanId string `json:"plan_id"`
}
