/*
 * Square Connect API
 *
 * Client library for accessing the Square Connect APIs
 *
 * API version: 2.0
 * Contact: developers@squareup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package square

// V1Variation
type V1Variation struct {
	// The item variation's unique ID.
	Id string `json:"id,omitempty"`
	// The item variation's name.
	Name string `json:"name,omitempty"`
	// The ID of the variation's associated item.
	ItemId string `json:"item_id,omitempty"`
	// Indicates the variation's list position when displayed in Square Point of Sale and the merchant dashboard. If more than one variation for the same item has the same ordinal value, those variations are displayed in alphabetical order
	Ordinal int32 `json:"ordinal,omitempty"`
	// Indicates whether the item variation's price is fixed or determined at the time of sale. See [V1VariationPricingType](#type-v1variationpricingtype) for possible values
	PricingType string `json:"pricing_type,omitempty"`
	PriceMoney *V1Money `json:"price_money,omitempty"`
	// The item variation's SKU, if any.
	Sku string `json:"sku,omitempty"`
	// If true, inventory tracking is active for the variation.
	TrackInventory bool `json:"track_inventory,omitempty"`
	// Indicates whether the item variation displays an alert when its inventory quantity is less than or equal to its inventory_alert_threshold. See [V1VariationInventoryAlertType](#type-v1variationinventoryalerttype) for possible values
	InventoryAlertType string `json:"inventory_alert_type,omitempty"`
	// If the inventory quantity for the variation is less than or equal to this value and inventory_alert_type is LOW_QUANTITY, the variation displays an alert in the merchant dashboard.
	InventoryAlertThreshold int32 `json:"inventory_alert_threshold,omitempty"`
	// Arbitrary metadata associated with the variation. Cannot exceed 255 characters.
	UserData string `json:"user_data,omitempty"`
	// The ID of the CatalogObject in the Connect v2 API. Objects that are shared across multiple locations share the same v2 ID.
	V2Id string `json:"v2_id,omitempty"`
}
