/*
 * Square Connect API
 *
 * Client library for accessing the Square Connect APIs
 *
 * API version: 2.0
 * Contact: developers@squareup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package square

// Represents a single physical count, inventory, adjustment, or transfer that is part of the history of inventory changes for a particular `CatalogObject`.
type InventoryChange struct {
	// Indicates how the inventory change was applied. See `InventoryChangeType` for all possible values. See [InventoryChangeType](#type-inventorychangetype) for possible values
	Type_ string `json:"type,omitempty"`
	PhysicalCount *InventoryPhysicalCount `json:"physical_count,omitempty"`
	Adjustment *InventoryAdjustment `json:"adjustment,omitempty"`
	Transfer *InventoryTransfer `json:"transfer,omitempty"`
}
