/*
 * Square Connect API
 *
 * Client library for accessing the Square Connect APIs
 *
 * API version: 2.0
 * Contact: developers@squareup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package square

// Describes a `DeleteInvoice` request.
type DeleteInvoiceRequest struct {
	// The version of the [invoice](https://developer.squareup.com/reference/square_2024-07-17/objects/Invoice) to delete. If you do not know the version, you can call [GetInvoice](https://developer.squareup.com/reference/square_2024-07-17/invoices-api/get-invoice) or  [ListInvoices](https://developer.squareup.com/reference/square_2024-07-17/invoices-api/list-invoices).
	Version int32 `json:"version,omitempty"`
}
