/*
 * Square Connect API
 *
 * Client library for accessing the Square Connect APIs
 *
 * API version: 2.0
 * Contact: developers@squareup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package square

// The response to a request for a set of `TeamMemberWage` objects. Contains a set of `TeamMemberWage`.
type ListTeamMemberWagesResponse struct {
	// A page of Team Member Wage results.
	TeamMemberWages []TeamMemberWage `json:"team_member_wages,omitempty"`
	// Value supplied in the subsequent request to fetch the next next page of Team Member Wage results.
	Cursor string `json:"cursor,omitempty"`
	// Any errors that occurred during the request.
	Errors []ModelError `json:"errors,omitempty"`
}
