/*
 * Square Connect API
 *
 * Client library for accessing the Square Connect APIs
 *
 * API version: 2.0
 * Contact: developers@squareup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package square

type V1BankAccountType string

// List of V1BankAccountType
const (
	BUSINESS_CHECKING_V1BankAccountType V1BankAccountType = "BUSINESS_CHECKING"
	CHECKING_V1BankAccountType V1BankAccountType = "CHECKING"
	INVESTMENT_V1BankAccountType V1BankAccountType = "INVESTMENT"
	LOAN_V1BankAccountType V1BankAccountType = "LOAN"
	SAVINGS_V1BankAccountType V1BankAccountType = "SAVINGS"
	OTHER_V1BankAccountType V1BankAccountType = "OTHER"
)
