/*
 * Square Connect API
 *
 * Client library for accessing the Square Connect APIs
 *
 * API version: 2.0
 * Contact: developers@squareup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package square

// Filter events by loyalty account.
type LoyaltyEventLoyaltyAccountFilter struct {
	// The ID of the [loyalty account](https://developer.squareup.com/reference/square_2024-07-17/objects/LoyaltyAccount) associated with loyalty events.
	LoyaltyAccountId string `json:"loyalty_account_id"`
}
