/*
 * Square Connect API
 *
 * Client library for accessing the Square Connect APIs
 *
 * API version: 2.0
 * Contact: developers@squareup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package square
// LocationCapability : The capabilities a location may have.
type LocationCapability string

// List of LocationCapability
const (
	PROCESSING_LocationCapability LocationCapability = "CREDIT_CARD_PROCESSING"
)
