/*
 * Square Connect API
 *
 * Client library for accessing the Square Connect APIs
 *
 * API version: 2.0
 * Contact: developers@squareup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package square

type V1FeeCalculationPhase string

// List of V1FeeCalculationPhase
const (
	FEE_SUBTOTAL_PHASE_V1FeeCalculationPhase V1FeeCalculationPhase = "FEE_SUBTOTAL_PHASE"
	OTHER_V1FeeCalculationPhase V1FeeCalculationPhase = "OTHER"
	FEE_TOTAL_PHASE_V1FeeCalculationPhase V1FeeCalculationPhase = "FEE_TOTAL_PHASE"
)
