/*
 * Square Connect API
 *
 * Client library for accessing the Square Connect APIs
 *
 * API version: 2.0
 * Contact: developers@squareup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package square

// CatalogModifierListModifierType : Defines the type of `CatalogModifierList`.
type CatalogModifierListModifierType string

// List of CatalogModifierListModifierType
const (
	LIST_CatalogModifierListModifierType CatalogModifierListModifierType = "LIST"
	TEXT_CatalogModifierListModifierType CatalogModifierListModifierType = "TEXT"
)
