/*
 * Square Connect API
 *
 * Client library for accessing the Square Connect APIs
 *
 * API version: 2.0
 * Contact: developers@squareup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package square

type V1ListEmployeesRequestStatus string

// List of V1ListEmployeesRequestStatus
const (
	ACTIVE_V1ListEmployeesRequestStatus V1ListEmployeesRequestStatus = "ACTIVE"
	INACTIVE_V1ListEmployeesRequestStatus V1ListEmployeesRequestStatus = "INACTIVE"
)
