/*
 * Square Connect API
 *
 * Client library for accessing the Square Connect APIs
 *
 * API version: 2.0
 * Contact: developers@squareup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package square

type DisputeEvidence struct {
	// The Square-generated ID of the evidence.
	EvidenceId string `json:"evidence_id,omitempty"`
	// The ID of the dispute the evidence is associated with.
	DisputeId string `json:"dispute_id,omitempty"`
	// The time when the next action is due, in RFC 3339 format.
	UploadedAt string `json:"uploaded_at,omitempty"`
	// The type of the evidence. See [DisputeEvidenceType](#type-disputeevidencetype) for possible values
	EvidenceType string `json:"evidence_type,omitempty"`
}
