/*
 * Square Connect API
 *
 * Client library for accessing the Square Connect APIs
 *
 * API version: 2.0
 * Contact: developers@squareup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package square

type V1ListCashDrawerShiftsRequest struct {
	// The order in which cash drawer shifts are listed in the response, based on their created_at field. Default value: ASC See [SortOrder](#type-sortorder) for possible values
	Order string `json:"order,omitempty"`
	// The beginning of the requested reporting period, in ISO 8601 format. Default value: The current time minus 90 days.
	BeginTime string `json:"begin_time,omitempty"`
	// The beginning of the requested reporting period, in ISO 8601 format. Default value: The current time.
	EndTime string `json:"end_time,omitempty"`
}
