/*
 * Square Connect API
 *
 * Client library for accessing the Square Connect APIs
 *
 * API version: 2.0
 * Contact: developers@squareup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package square

// Represents a change in state or quantity of product inventory at a particular time and location.
type InventoryAdjustment struct {
	// A unique ID generated by Square for the `InventoryAdjustment`.
	Id string `json:"id,omitempty"`
	// An optional ID provided by the application to tie the `InventoryAdjustment` to an external system.
	ReferenceId string `json:"reference_id,omitempty"`
	// The `InventoryState` of the related quantity of items before the adjustment. See [InventoryState](#type-inventorystate) for possible values
	FromState string `json:"from_state,omitempty"`
	// The `InventoryState` of the related quantity of items after the adjustment. See [InventoryState](#type-inventorystate) for possible values
	ToState string `json:"to_state,omitempty"`
	// The Square ID of the `Location` where the related quantity of items are being tracked.
	LocationId string `json:"location_id,omitempty"`
	// The Square generated ID of the `CatalogObject` being tracked.
	CatalogObjectId string `json:"catalog_object_id,omitempty"`
	// The `CatalogObjectType` of the `CatalogObject` being tracked. Tracking is only supported for the `ITEM_VARIATION` type.
	CatalogObjectType string `json:"catalog_object_type,omitempty"`
	// The number of items affected by the adjustment as a decimal string. Can support up to 5 digits after the decimal point.
	Quantity string `json:"quantity,omitempty"`
	TotalPriceMoney *Money `json:"total_price_money,omitempty"`
	// A client-generated timestamp in RFC 3339 format that indicates when the adjustment took place. For write actions, the `occurred_at` timestamp cannot be older than 24 hours or in the future relative to the time of the request.
	OccurredAt string `json:"occurred_at,omitempty"`
	// A read-only timestamp in RFC 3339 format that indicates when Square received the adjustment.
	CreatedAt string `json:"created_at,omitempty"`
	Source *SourceApplication `json:"source,omitempty"`
	// The Square ID of the `Employee` responsible for the inventory adjustment.
	EmployeeId string `json:"employee_id,omitempty"`
	// The read-only Square ID of the [Transaction][#type-transaction] that caused the adjustment. Only relevant for payment-related state transitions.
	TransactionId string `json:"transaction_id,omitempty"`
	// The read-only Square ID of the [Refund][#type-refund] that caused the adjustment. Only relevant for refund-related state transitions.
	RefundId string `json:"refund_id,omitempty"`
	// The read-only Square ID of the purchase order that caused the adjustment. Only relevant for state transitions from the Square for Retail app.
	PurchaseOrderId string `json:"purchase_order_id,omitempty"`
	// The read-only Square ID of the Square goods receipt that caused the adjustment. Only relevant for state transitions from the Square for Retail app.
	GoodsReceiptId string `json:"goods_receipt_id,omitempty"`
}
