/*
 * Square Connect API
 *
 * Client library for accessing the Square Connect APIs
 *
 * API version: 2.0
 * Contact: developers@squareup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package square

import "encoding/json"

type CheckoutMerchantSettingsPaymentMethods struct {
	ApplePay         json.RawMessage `json:"apple_pay,omitempty"`
	GooglePay        json.RawMessage `json:"google_pay,omitempty"`
	CashApp          json.RawMessage `json:"cash_app,omitempty"`
	AfterpayClearpay json.RawMessage `json:"afterpay_clearpay,omitempty"`
}
