/*
 * Square Connect API
 *
 * Client library for accessing the Square Connect APIs
 *
 * API version: 2.0
 * Contact: developers@squareup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package square

type V1EmployeeStatus string

// List of V1EmployeeStatus
const (
	ACTIVE_V1EmployeeStatus V1EmployeeStatus = "ACTIVE"
	INACTIVE_V1EmployeeStatus V1EmployeeStatus = "INACTIVE"
)
