/*
 * Square Connect API
 *
 * Client library for accessing the Square Connect APIs
 *
 * API version: 2.0
 * Contact: developers@squareup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package square

// Criteria to sort events by.
type SearchEventsSort struct {
	// Sort events by event types.
	Field string `json:"field,omitempty"`
	// The order to use for sorting the events.
	Order string `json:"order,omitempty"`
}
