/*
 * Square Connect API
 *
 * Client library for accessing the Square Connect APIs
 *
 * API version: 2.0
 * Contact: developers@squareup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package square

type LoyaltyReward struct {
	// The Square-assigned ID of the loyalty reward.
	Id string `json:"id,omitempty"`
	// The status of a loyalty reward. See [LoyaltyRewardStatus](#type-loyaltyrewardstatus) for possible values
	Status string `json:"status,omitempty"`
	// The Square-assigned ID of the `loyalty account` to which the reward belongs.
	LoyaltyAccountId string `json:"loyalty_account_id"`
	// The Square-assigned ID of the `reward tier` used to create the reward.
	RewardTierId string `json:"reward_tier_id"`
	// The number of loyalty points used for the reward.
	Points int32 `json:"points,omitempty"`
	// The Square-assigned ID of the `order` to which the reward is attached.
	OrderId string `json:"order_id,omitempty"`
	// The timestamp when the reward was created, in RFC 3339 format.
	CreatedAt string `json:"created_at,omitempty"`
	// The timestamp when the reward was last updated, in RFC 3339 format.
	UpdatedAt string `json:"updated_at,omitempty"`
	// The timestamp when the reward was redeemed, in RFC 3339 format.
	RedeemedAt string `json:"redeemed_at,omitempty"`
}
