/*
 * Square Connect API
 *
 * Client library for accessing the Square Connect APIs
 *
 * API version: 2.0
 * Contact: developers@squareup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package square

// V1ModifierList
type V1ModifierList struct {
	// The modifier list's unique ID.
	Id string `json:"id,omitempty"`
	// The modifier list's name.
	Name string `json:"name,omitempty"`
	// Indicates whether MULTIPLE options or a SINGLE option from the modifier list can be applied to a single item. See [V1ModifierListSelectionType](#type-v1modifierlistselectiontype) for possible values
	SelectionType string `json:"selection_type,omitempty"`
	// The options included in the modifier list.
	ModifierOptions []V1ModifierOption `json:"modifier_options,omitempty"`
	// The ID of the CatalogObject in the Connect v2 API. Objects that are shared across multiple locations share the same v2 ID.
	V2Id string `json:"v2_id,omitempty"`
}
