/*
 * Square Connect API
 *
 * Client library for accessing the Square Connect APIs
 *
 * API version: 2.0
 * Contact: developers@squareup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package square

type V1CashDrawerShiftEventType string

// List of V1CashDrawerShiftEventType
const (
	OPEN_V1CashDrawerShiftEventType V1CashDrawerShiftEventType = "OPEN"
	ENDED_V1CashDrawerShiftEventType V1CashDrawerShiftEventType = "ENDED"
	CLOSED_V1CashDrawerShiftEventType V1CashDrawerShiftEventType = "CLOSED"
)
