/*
 * Square Connect API
 *
 * Client library for accessing the Square Connect APIs
 *
 * API version: 2.0
 * Contact: developers@squareup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package square

// The range of a number value between the specified lower and upper bounds.
type ModelRange struct {
	// The lower bound of the number range.
	Min string `json:"min,omitempty"`
	// The upper bound of the number range.
	Max string `json:"max,omitempty"`
}
