/*
 * Square Connect API
 *
 * Client library for accessing the Square Connect APIs
 *
 * API version: 2.0
 * Contact: developers@squareup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package square

type V1VariationInventoryAlertType string

// List of V1VariationInventoryAlertType
const (
	LOW_QUANTITY_V1VariationInventoryAlertType V1VariationInventoryAlertType = "LOW_QUANTITY"
	NONE_V1VariationInventoryAlertType V1VariationInventoryAlertType = "NONE"
	INVESTMENT_V1VariationInventoryAlertType V1VariationInventoryAlertType = "INVESTMENT"
	LOAN_V1VariationInventoryAlertType V1VariationInventoryAlertType = "LOAN"
	SAVINGS_V1VariationInventoryAlertType V1VariationInventoryAlertType = "SAVINGS"
	OTHER_V1VariationInventoryAlertType V1VariationInventoryAlertType = "OTHER"
)
