/*
 * Square Connect API
 *
 * Client library for accessing the Square Connect APIs
 *
 * API version: 2.0
 * Contact: developers@squareup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package square

// A line item modifier being returned.
type OrderReturnLineItemModifier struct {
	// Unique ID that identifies the return modifier only within this order.
	Uid string `json:"uid,omitempty"`
	// `uid` of the Modifier from the LineItem from the Order which contains the original sale of this line item modifier.
	SourceModifierUid string `json:"source_modifier_uid,omitempty"`
	// The catalog object id referencing `CatalogModifier`.
	CatalogObjectId string `json:"catalog_object_id,omitempty"`
	// The name of the item modifier.
	Name string `json:"name,omitempty"`
	BasePriceMoney *Money `json:"base_price_money,omitempty"`
	TotalPriceMoney *Money `json:"total_price_money,omitempty"`
}
