/*
 * Square Connect API
 *
 * Client library for accessing the Square Connect APIs
 *
 * API version: 2.0
 * Contact: developers@squareup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package square

// The hourly wage rate used to compensate an employee for this shift.
type ShiftWage struct {
	// The name of the job performed during this shift. Square labor-reporting UIs may group shifts together by title.
	Title string `json:"title,omitempty"`
	HourlyRate *Money `json:"hourly_rate,omitempty"`
}
