/*
 * Square Connect API
 *
 * Client library for accessing the Square Connect APIs
 *
 * API version: 2.0
 * Contact: developers@squareup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package square
// InlineTypes : Object types to inline under their respective parent object in certain connect v2 responses
type InlineTypes string

// List of InlineTypes
const (
	NONE_InlineTypes InlineTypes = "INLINE_NONE"
	VARIATIONS_InlineTypes InlineTypes = "INLINE_VARIATIONS"
	ALL_InlineTypes InlineTypes = "INLINE_ALL"
)
