/*
 * Square Connect API
 *
 * Client library for accessing the Square Connect APIs
 *
 * API version: 2.0
 * Contact: developers@squareup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package square

type V1ListEmployeesRequest struct {
	// The order in which employees are listed in the response, based on their created_at field.      Default value: ASC See [SortOrder](#type-sortorder) for possible values
	Order string `json:"order,omitempty"`
	// If filtering results by their updated_at field, the beginning of the requested reporting period, in ISO 8601 format
	BeginUpdatedAt string `json:"begin_updated_at,omitempty"`
	// If filtering results by there updated_at field, the end of the requested reporting period, in ISO 8601 format.
	EndUpdatedAt string `json:"end_updated_at,omitempty"`
	// If filtering results by their created_at field, the beginning of the requested reporting period, in ISO 8601 format.
	BeginCreatedAt string `json:"begin_created_at,omitempty"`
	// If filtering results by their created_at field, the end of the requested reporting period, in ISO 8601 format.
	EndCreatedAt string `json:"end_created_at,omitempty"`
	// If provided, the endpoint returns only employee entities with the specified status (ACTIVE or INACTIVE). See [V1ListEmployeesRequestStatus](#type-v1listemployeesrequeststatus) for possible values
	Status string `json:"status,omitempty"`
	// If provided, the endpoint returns only employee entities with the specified external_id.
	ExternalId string `json:"external_id,omitempty"`
	// The maximum integer number of employee entities to return in a single response. Default 100, maximum 200.
	Limit int32 `json:"limit,omitempty"`
	// A pagination cursor to retrieve the next set of results for your original query to the endpoint.
	BatchToken string `json:"batch_token,omitempty"`
}
