/*
 * Square Connect API
 *
 * Client library for accessing the Square Connect APIs
 *
 * API version: 2.0
 * Contact: developers@squareup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package square

type V1ModifierListSelectionType string

// List of V1ModifierListSelectionType
const (
	SINGLE_V1ModifierListSelectionType V1ModifierListSelectionType = "SINGLE"
	MULTIPLE_V1ModifierListSelectionType V1ModifierListSelectionType = "MULTIPLE"
)
