/*
 * Square Connect API
 *
 * Client library for accessing the Square Connect APIs
 *
 * API version: 2.0
 * Contact: developers@squareup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package square

type V1VariationPricingType string

// List of V1VariationPricingType
const (
	FIXED_PRICING_V1VariationPricingType V1VariationPricingType = "FIXED_PRICING"
	VARIABLE_PRICING_V1VariationPricingType V1VariationPricingType = "VARIABLE_PRICING"
)
