/*
 * Square Connect API
 *
 * Client library for accessing the Square Connect APIs
 *
 * API version: 2.0
 * Contact: developers@squareup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package square

// Defines an appointment segment of a booking.
type AppointmentSegment struct {
	// The time span in minutes of an appointment segment.
	DurationMinutes int32 `json:"duration_minutes"`
	// The ID of the `CatalogItemVariation` object representing the service booked in this segment.
	ServiceVariationId string `json:"service_variation_id"`
	// The ID of the `TeamMember` object representing the team member booked in this segment.
	TeamMemberId string `json:"team_member_id"`
	// The current version of the item variation representing the service booked in this segment.
	ServiceVariationVersion int64 `json:"service_variation_version"`
}
