/*
 * Square Connect API
 *
 * Client library for accessing the Square Connect APIs
 *
 * API version: 2.0
 * Contact: developers@squareup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package square

type V1ListEmployeeRolesRequest struct {
	// The order in which employees are listed in the response, based on their created_at field.Default value: ASC See [SortOrder](#type-sortorder) for possible values
	Order string `json:"order,omitempty"`
	// The maximum integer number of employee entities to return in a single response. Default 100, maximum 200.
	Limit int32 `json:"limit,omitempty"`
	// A pagination cursor to retrieve the next set of results for your original query to the endpoint.
	BatchToken string `json:"batch_token,omitempty"`
}
