/*
 * Square Connect API
 *
 * Client library for accessing the Square Connect APIs
 *
 * API version: 2.0
 * Contact: developers@squareup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package square

// Provides information about a loyalty event.  For more information, see [Loyalty events](/docs/loyalty-api/overview/#loyalty-events).
type LoyaltyEvent struct {
	// The Square-assigned ID of the loyalty event.
	Id string `json:"id"`
	// The type of the loyalty event. See [LoyaltyEventType](#type-loyaltyeventtype) for possible values
	Type_ string `json:"type"`
	// The timestamp when the event was created, in RFC 3339 format.
	CreatedAt string `json:"created_at"`
	AccumulatePoints *LoyaltyEventAccumulatePoints `json:"accumulate_points,omitempty"`
	CreateReward *LoyaltyEventCreateReward `json:"create_reward,omitempty"`
	RedeemReward *LoyaltyEventRedeemReward `json:"redeem_reward,omitempty"`
	DeleteReward *LoyaltyEventDeleteReward `json:"delete_reward,omitempty"`
	AdjustPoints *LoyaltyEventAdjustPoints `json:"adjust_points,omitempty"`
	// The ID of the `loyalty account` in which the event occurred.
	LoyaltyAccountId string `json:"loyalty_account_id"`
	// The ID of the `location` where the event occurred.
	LocationId string `json:"location_id,omitempty"`
	// Defines whether the event was generated by the Square Point of Sale. See [LoyaltyEventSource](#type-loyaltyeventsource) for possible values
	Source string `json:"source"`
	ExpirePoints *LoyaltyEventExpirePoints `json:"expire_points,omitempty"`
	OtherEvent *LoyaltyEventOther `json:"other_event,omitempty"`
}
