/*
 * Square Connect API
 *
 * Client library for accessing the Square Connect APIs
 *
 * API version: 2.0
 * Contact: developers@squareup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package square

// Provides information about the application used to generate a change.
type SourceApplication struct {
	// Read-only `Product` type for the application. See [Product](#type-product) for possible values
	Product string `json:"product,omitempty"`
	// Read-only Square ID assigned to the application. Only used for `Product` type `EXTERNAL_API`.
	ApplicationId string `json:"application_id,omitempty"`
	// Read-only display name assigned to the application (e.g. `\"Custom Application\"`, `\"Square POS 4.74 for Android\"`).
	Name string `json:"name,omitempty"`
}
